### ISSUE TITLE
"Not Found" error

### ISSUE THREAD

**Issue by RichardLitt** [IonicaBizau/github-labeller#11]
I am getting this error, and I am not sure why: 

``` js
$ github-labeller -r multiformats/multiformats --token <valid_token> -c githubLabels.json 
error Failed to add label difficulty:moderate to multiformats/multiformats. Not Found
error Failed to add label needs review to multiformats/multiformats. Not Found
error Failed to add label difficulty:hard to multiformats/multiformats. Not Found
error Failed to add label difficulty:easy to multiformats/multiformats. Not Found
info  Done.
```

`githubLabels.json` looks like this:

``` json
[
  {
    "name": "needs review",
    "color": "0052cc"
  },
  {
    "name": "difficulty:easy",
    "color": "bfe5bf"
  },
  {
    "name": "difficulty:moderate",
    "color": "bfe5bf"
  },
  {
    "name": "difficulty:hard",
    "color": "bfe5bf"
  }
]
```

Any ideas? I am the admin of the repo and organization in question.

**Comment by IonicaBizau** [comment]
Interesting. Does your token have any scope enabled?

**Comment by RichardLitt** [comment]
No; should it have one?

**Comment by IonicaBizau** [comment]
@RichardLitt Obviously yes. :grin: Probably it should be better documented.

A scopeless token can only access public information. Add the `repo` scope and it should be working. I did email GitHub regarding that confusing `Not found` error, but they said it's by design. I would expect a 403 or so.

**Comment by RichardLitt** [comment]
Fixed!
