### ISSUE TITLE
Allow overwriting labels

### ISSUE THREAD

**Issue by wooorm** [IonicaBizau/github-labeller#4]
First of all: maybe this should already work, but for some other reason this failed for me.

Second: cool project!

Next, my problem:

<img width="754" alt="labels" src="https://cloud.githubusercontent.com/assets/944406/12221584/6353c426-b7a1-11e5-8f5a-e975702a040c.png">

(`lbl` is an alias: `alias lbl="github-labeller -t some-token"`) where some-token is of course replaced. :wink:)

I am only able to create new labels but I cannot overwrite them when they already exist. This means I cannot set new colours for the default labels (without deleting them all, which I did before the first example in the attached image).

Is this something you think is in the scope of this project, and plan on implementing?

**Comment by IonicaBizau** [comment]
> Is this something you think is in the scope of this project, and plan on implementing?

Would be a handy feature to be able to update existing labels. Thanks for the idea. I would happily accept contributions in this direction. :sparkle:

**Comment by wooorm** [comment]
Working on this, this is going to be awesome!

**Comment by IonicaBizau** [comment]
@wooorm Thanks! Great! :+1:
